name: Build LunaOS ISO
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:

      - name: Prepare container
        run: |
          pacman -Syu --noconfirm --needed base-devel git sudo archiso

          # Chaotic-AUR repository keys
          pacman-key --init
          pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
          pacman-key --lsign-key 3056513887B78AEB
          pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' 'https://github.com/Boria138/lunaos-repo-actions/releases/download/lunaos-repo/lunaos-mirrorlist-2-1-x86_64.pkg.tar.zst' 'https://github.com/Boria138/lunaos-repo-actions/releases/download/lunaos-repo/lunaos-keyring-2-1-any.pkg.tar.zst'

          # Enable the multilib repository
          cat << EOM >> /etc/pacman.conf
          [multilib]
          Include = /etc/pacman.d/mirrorlist

          [lunaos-repo]
          Include = /etc/pacman.d/lunaos-mirrorlist

          [chaotic-aur]
          Include = /etc/pacman.d/chaotic-mirrorlist
          EOM

          pacman -Sy

          useradd -m user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R /tmp
          chown user -R ..

      - name: Build LunaOS ISO
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/iso/lunaos-archiso.git
          cd /__w/lunaos-repo-actions/lunaos-archiso
          chown user -R ..
          su user -c "yes '' | mkarchiso -v -w . -o build ."

      - name: Checkout
        uses: actions/checkout@v3

      - name: Release all packages to Github Releases Mirror
        uses: softprops/action-gh-release@v1
        with:
          tag_name: lunaos-iso
          files: /__w/lunaos-repo-actions/lunaos-archiso/build/*
