name: LunaOS Repo Update
on:
  schedule:
    - cron: '17 */12 * * *' # “At minute 17 past every 12th hour.”
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-repo:
    runs-on: ubuntu-latest
    container: 
      image: archlinux:base-devel

    env:
      PKGDEST: "/tmp/lunaos-repo"
      repo: "lunaos-repo"
      arch_repo: "x86_64"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GPG_PASSPHRASE: ${{ secrets.PASSPHRASE }}

    steps:

      - name: Prepare container
        run: |
          pacman -Syu --noconfirm --needed base-devel git sudo wget sshpass gnupg

          wget https://raw.githubusercontent.com/Boria138/lunaos-repo-actions/main/update-repo.sh -P /__w/lunaos-repo-actions
          wget https://raw.githubusercontent.com/Boria138/lunaos-repo-actions/main/sign.sh -P /__w/lunaos-repo-actions
          wget https://raw.githubusercontent.com/Boria138/lunaos-repo-actions/main/lunaos-keyring.pkg.tar.zst -P /__w/lunaos-repo-actions

          # Use all available threads to build a package
          sed -i 's/#MAKEFLAGS="-j2"/MAKEFLAGS="-j$(nproc) -l$(nproc)"/g' /etc/makepkg.conf
          
          # Chaotic-AUR and your repository keys
          pacman-key --init
          pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
          pacman-key --recv-key 78B2BAAB82C8D511
          pacman-key --lsign-key 3056513887B78AEB
          pacman-key --lsign-key 78B2BAAB82C8D511
          pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' /__w/lunaos-repo-actions/lunaos-keyring.pkg.tar.zst

          # Enable the multilib repository
          cat << EOM >> /etc/pacman.conf
          [multilib]
          Include = /etc/pacman.d/mirrorlist

          [chaotic-aur]
          Include = /etc/pacman.d/chaotic-mirrorlist
          EOM

          pacman -Sy

          useradd -m user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          echo "PACKAGER=\"Boris Yumankulov <boriabloger@protonmail.com>\"" >> /etc/makepkg.conf
          echo "GPGKEY=\"78B2BAAB82C8D511\"" >> /etc/makepkg.conf
          chown user -R /tmp
          chown user -R ..

      - name: Import GPG private key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          trust_level: 5

      - name: Keys List
        run: |
          gpg -K

      - name: Build Calamares
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/system/base/calamares/calamares.git
          cd /__w/lunaos-repo-actions/calamares
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build LunaOS Calamares Config
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/system/base/calamares/lunaos-calamares-config.git
          cd /__w/lunaos-repo-actions/lunaos-calamares-config
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"
      
      - name: Build LunaOS Branding
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/system/base/lunaos-branding.git
          cd /__w/lunaos-repo-actions/lunaos-branding
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build LunaOS Neofetch
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/lunaos-neofetch.git
          cd /__w/lunaos-repo-actions/lunaos-neofetch
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build LunaOS Keyring
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/system/base/lunaos-keyring.git
          cd /__w/lunaos-repo-actions/lunaos-keyring
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build LunaOS Mirrorlist
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/system/base/lunaos-mirrorlist.git
          cd /__w/lunaos-repo-actions/lunaos-mirrorlist
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build cachyos-ananicy-rules-git 
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/cachyos-ananicy-rules-git.git
          cd /__w/lunaos-repo-actions/cachyos-ananicy-rules-git 
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build LunaOS Settings
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/system/base/lunaos-settings.git
          cd /__w/lunaos-repo-actions/lunaos-settings
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build LunaOS Zram Defaults
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/lunaos-zram-defaults.git
          cd /__w/lunaos-repo-actions/lunaos-zram-defaults
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build Nautilus Backspace Back Extension 
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/gnome/nautilus-backspace-back-extension.git
          cd /__w/lunaos-repo-actions/nautilus-backspace-back-extension
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build Nautilus Admin Extension
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/nautilus-admin-gtk4.git
          cd /__w/lunaos-repo-actions/nautilus-admin-gtk4
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build Nautilus Copy Path Extension
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/nautilus-copy-path.git
          cd /__w/lunaos-repo-actions/nautilus-copy-path
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build Just Perfection Gnome Shell Extension
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/gnome-shell-extension-just-perfection-desktop.git
          cd /__w/lunaos-repo-actions/gnome-shell-extension-just-perfection-desktop
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build LunaOS Gnome Settings 
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/gnome/lunaos-gnome-settings.git
          cd /__w/lunaos-repo-actions/lunaos-gnome-settings
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build LunaOS Plasma Settings 
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/plasma/lunaos-plasma-settings.git
          cd /__w/lunaos-repo-actions/lunaos-plasma-settings
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build hplip-plugin
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/hplip-plugin.git
          cd /__w/lunaos-repo-actions/hplip-plugin
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build optimus-manger-qt-kde
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/optimus-manager-qt-kde.git
          cd /__w/lunaos-repo-actions/optimus-manager-qt-kde
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build Nvidia 390xx meta
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/drivers/nvidia/nvidia-390xx-meta.git
          cd /__w/lunaos-repo-actions/nvidia-390xx-meta
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build Nvidia 470xx meta
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/drivers/nvidia/nvidia-470xx-meta.git
          cd /__w/lunaos-repo-actions/nvidia-470xx-meta
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build Nvidia meta
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/drivers/nvidia/nvidia-meta.git
          cd /__w/lunaos-repo-actions/nvidia-meta
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build Nvidia-Tweaks
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/nvidia-tweaks.git
          cd /__w/lunaos-repo-actions/nvidia-tweaks
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -d"

      - name: Build Nouveau Reclocking 
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/drivers/nvidia/nouveau-reclocking.git
          cd /__w/lunaos-repo-actions/nouveau-reclocking
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build amf-amdgpu-pro
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/amdgpu-pro-installer.git
          cd /__w/lunaos-repo-actions/amdgpu-pro-installer
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build laptop-mode-tools
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/laptop-mode-tools.git
          cd /__w/lunaos-repo-actions/laptop-mode-tools
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build hid-sony-panic-fix-dkms
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/hid-sony-panic-fix-dkms.git
          cd /__w/lunaos-repo-actions/hid-sony-panic-fix-dkms
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build e1000e-dkms
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/e1000e-dkms.git
          cd /__w/lunaos-repo-actions/e1000e-dkms
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build 8188eu-dkms
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/8188eu-dkms.git
          cd /__w/lunaos-repo-actions/8188eu-dkms
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build PortProton
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/portproton.git 
          cd /__w/lunaos-repo-actions/portproton
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build StartWine
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/startwine.git 
          cd /__w/lunaos-repo-actions/startwine
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build GRUB Hook
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/grub-hook.git 
          cd /__w/lunaos-repo-actions/grub-hook
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build GRUB Meta
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/meta-packages/grub-meta.git
          cd /__w/lunaos-repo-actions/grub-meta
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -d"

      - name: Build Kvantm LibAdwaita theme
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/kvantum-theme-libadwaita-git.git
          cd /__w/lunaos-repo-actions/kvantum-theme-libadwaita-git
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build Kvantum Colloid theme
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/gnome/colloid-kvantum-theme.git
          cd /__w/lunaos-repo-actions/colloid-kvantum-theme
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build winesync-dkms
        run: |
          cd /__w/lunaos-repo-actions
          git clone https://aur.archlinux.org/winesync.git
          cd /__w/lunaos-repo-actions/winesync
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Sign lunaos repo
        run: |
          cd $PKGDEST
          sh /__w/lunaos-repo-actions/sign.sh

      - name: Update lunaos repo
        run: |
          cd $PKGDEST
          sh /__w/lunaos-repo-actions/update-repo.sh

      - name: Checkout
        uses: actions/checkout@v3

      - name: Release all packages to Github Releases Mirror
        uses: softprops/action-gh-release@v1
        with:
          tag_name: lunaos-repo
          files: /tmp/lunaos-repo/*

      - name: Deploy all packages to surge.sh Mirror
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'lunaos-repo.surge.sh'
          project: '/tmp/lunaos-repo/'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
