name: LunaOS Repo Update
on:
  schedule:
    - cron: '17 */12 * * *' # “At minute 17 past every 12th hour.”
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    permissions:
      contents: write

    container:
      image: archlinux:base-devel
      options: --privileged
    
    env:
      PKGDEST: "/tmp/lunaos-repo"
      repo: "lunaos-repo"
      arch_repo: "x86_64"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GPG_PASSPHRASE: ${{ secrets.PASSPHRASE }}

    steps:

      - name: Prepare container
        run: |
          pacman -Syuu --noconfirm --disable-download-timeout --needed git wget gnupg

          wget https://raw.githubusercontent.com/Lenuma-inc/lunaos-repo/main/update-repo.sh -P /__w/lunaos-repo
          wget https://raw.githubusercontent.com/Lenuma-inc/lunaos-repo/main/sign.sh -P /__w/lunaos-repo

          # Use all available threads to build a package
          sed -i 's/#MAKEFLAGS="-j2"/MAKEFLAGS="-j$(nproc) -l$(nproc)"/g' /etc/makepkg.conf
          
          # Chaotic-AUR repository keys
          pacman-key --init
          pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
          pacman-key --lsign-key 3056513887B78AEB
          pacman -U --disable-download-timeout --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

          # Enable the multilib repository
          cat << EOM >> /etc/pacman.conf
          [multilib]
          Include = /etc/pacman.d/mirrorlist

          [chaotic-aur]
          Include = /etc/pacman.d/chaotic-mirrorlist
          EOM

          pacman -Sy --noconfirm --disable-download-timeout --needed rate-mirrors

          rate-mirrors --allow-root arch | tee /etc/pacman.d/mirrorlist
          rate-mirrors --allow-root chaotic-aur | tee /etc/pacman.d/chaotic-mirrorlist
          
          pacman -Sy

          useradd -m user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          echo "PACKAGER=\"LunaOS Team\"" >> /etc/makepkg.conf
          echo "GPGKEY=\"78B2BAAB82C8D511\"" >> /etc/makepkg.conf
          chown user -R /tmp
          chown user -R ..

      - name: Import GPG private key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          trust_level: 5

      - name: Build Calamares
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/system/base/calamares/calamares.git
          cd /__w/lunaos-repo/calamares
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build LunaOS Calamares Config
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/system/base/calamares/lunaos-calamares-config.git
          cd /__w/lunaos-repo/lunaos-calamares-config
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build TuneD balanced profile fix
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/tuned-balanced-fix
          cd /__w/lunaos-repo/tuned-balanced-fix
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build LunaOS Firefox Settings
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/firefox/lunaos-firefox-settings.git
          cd /__w/lunaos-repo/lunaos-firefox-settings
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"
      
      - name: Build LunaOS Branding
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/system/base/lunaos-branding.git
          cd /__w/lunaos-repo/lunaos-branding
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build LunaOS Neofetch
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/lunaos-neofetch.git
          cd /__w/lunaos-repo/lunaos-neofetch
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build LunaOS Wallpapers
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/lunaos-wallpapers.git
          cd /__w/lunaos-repo/lunaos-wallpapers
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build LunaOS Plymouth theme
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/lunaos-plymouth-theme.git
          cd /__w/lunaos-repo/lunaos-plymouth-theme
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build cachyos-systemd-boot-manager
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/systemd-boot-manager.git
          cd /__w/lunaos-repo/systemd-boot-manager
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build LunaOS Keyring
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/system/base/lunaos-keyring.git
          cd /__w/lunaos-repo/lunaos-keyring
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build LunaOS Mirrorlist
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/system/base/lunaos-mirrorlist.git
          cd /__w/lunaos-repo/lunaos-mirrorlist
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build cachyos-ananicy-rules-git 
        run: |
          cd /__w/lunaos-repo
          git clone https://aur.archlinux.org/cachyos-ananicy-rules-git.git
          cd /__w/lunaos-repo/cachyos-ananicy-rules-git 
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build LunaOS Settings
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/system/base/lunaos-settings.git
          cd /__w/lunaos-repo/lunaos-settings
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build LunaOS Zram Defaults
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/lunaos-zram-defaults.git
          cd /__w/lunaos-repo/lunaos-zram-defaults
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build Nautilus Backspace Back Extension 
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/gnome/nautilus-backspace-back-extension.git
          cd /__w/lunaos-repo/nautilus-backspace-back-extension
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build Nautilus Admin Extension
        run: |
          cd /__w/lunaos-repo
          git clone https://aur.archlinux.org/nautilus-admin-gtk4.git
          cd /__w/lunaos-repo/nautilus-admin-gtk4
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build Nautilus Copy Path Extension
        run: |
          cd /__w/lunaos-repo
          git clone https://aur.archlinux.org/nautilus-copy-path.git
          cd /__w/lunaos-repo/nautilus-copy-path
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build Just Perfection Gnome Shell Extension
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/gnome/gnome-extensions/gnome-shell-extension-just-perfection-desktop.git
          cd /__w/lunaos-repo/gnome-shell-extension-just-perfection-desktop
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build GPU profile selector Gnome Shell Extension
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/gnome/gnome-extensions/gnome-shell-extension-gpu-profile-selector-git.git 
          cd /__w/lunaos-repo/gnome-shell-extension-gpu-profile-selector-git
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build Blur my Shell Gnome Shell Extension
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/gnome/gnome-extensions/gnome-shell-extension-blur-my-shell.git 
          cd /__w/lunaos-repo/gnome-shell-extension-blur-my-shell
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build Dash to Dock Gnome Shell Extension
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/gnome/gnome-extensions/gnome-shell-extension-dash-to-dock.git 
          cd /__w/lunaos-repo/gnome-shell-extension-dash-to-dock
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build AppIndicator and KStatusNotifierItem Support Shell Extension
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/gnome/gnome-extensions/gnome-shell-extension-appindicator.git 
          cd /__w/lunaos-repo/gnome-shell-extension-appindicator
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build LunaOS Gnome Settings 
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/gnome/lunaos-gnome-settings.git
          cd /__w/lunaos-repo/lunaos-gnome-settings
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build Optimus GPU Switcher KDE Plasma Widget
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/plasma/optimus-gpu-switcher-kde-plasma-widget.git
          cd /__w/lunaos-repo/optimus-gpu-switcher-kde-plasma-widget
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build Otto kde theme
        run: |
          cd /__w/lunaos-repo
          git clone https://aur.archlinux.org/otto-kde-git.git
          cd /__w/lunaos-repo/otto-kde-git
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build LunaOS Plasma Settings 
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/plasma/lunaos-plasma-settings.git
          cd /__w/lunaos-repo/lunaos-plasma-settings
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build hplip-plugin
        run: |
          cd /__w/lunaos-repo
          git clone https://aur.archlinux.org/hplip-plugin.git
          cd /__w/lunaos-repo/hplip-plugin
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build optimus-manger-qt-kde
        run: |
          cd /__w/lunaos-repo
          git clone https://aur.archlinux.org/optimus-manager-qt-kde.git
          cd /__w/lunaos-repo/optimus-manager-qt-kde
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Install nvidia-390xx-settings deps
        run: pacman -Syu --needed --noconfirm git inetutils jansson gtk3 libxv libvdpau libxext

      - name: Build Nvidia 390xx drivers
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/herecura/packages/nvidia-390xx-dkms.git
          cd /__w/lunaos-repo/nvidia-390xx-dkms
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

          cd /__w/lunaos-repo
          git clone https://gitlab.com/herecura/packages/nvidia-390xx-utils.git
          cd /__w/lunaos-repo/nvidia-390xx-utils
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

          cd /__w/lunaos-repo
          git clone https://gitlab.com/herecura/packages/nvidia-390xx-settings.git
          cd /__w/lunaos-repo/nvidia-390xx-settings
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build Nvidia 390xx meta
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/drivers/nvidia/nvidia-390xx-meta.git
          cd /__w/lunaos-repo/nvidia-390xx-meta
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Install nvidia-470xx-settings deps
        run: pacman -Syu --needed --noconfirm git inetutils jansson gtk2 gtk3 libxv libvdpau libxext

      - name: Build Nvidia 470xx drivers
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/herecura/packages/nvidia-470xx-dkms.git
          cd /__w/lunaos-repo/nvidia-470xx-dkms
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

          cd /__w/lunaos-repo
          git clone https://gitlab.com/herecura/packages/nvidia-470xx-utils.git
          cd /__w/lunaos-repo/nvidia-470xx-utils
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

          cd /__w/lunaos-repo
          git clone https://gitlab.com/herecura/packages/nvidia-470xx-settings.git
          cd /__w/lunaos-repo/nvidia-470xx-settings
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build Nvidia 470xx meta
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/drivers/nvidia/nvidia-470xx-meta.git
          cd /__w/lunaos-repo/nvidia-470xx-meta
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build Nvidia meta
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/drivers/nvidia/nvidia-meta.git
          cd /__w/lunaos-repo/nvidia-meta
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -sd"

      - name: Build Nouveau Reclocking 
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/drivers/nvidia/nouveau-reclocking.git
          cd /__w/lunaos-repo/nouveau-reclocking
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build amf-amdgpu-pro
        run: |
          cd /__w/lunaos-repo
          git clone https://aur.archlinux.org/amdgpu-pro-installer.git
          cd /__w/lunaos-repo/amdgpu-pro-installer
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build hid-sony-panic-fix-dkms
        run: |
          cd /__w/lunaos-repo
          git clone https://aur.archlinux.org/hid-sony-panic-fix-dkms.git
          cd /__w/lunaos-repo/hid-sony-panic-fix-dkms
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build e1000e-dkms
        run: |
          cd /__w/lunaos-repo
          git clone https://aur.archlinux.org/e1000e-dkms.git
          cd /__w/lunaos-repo/e1000e-dkms
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build 8188eu-dkms
        run: |
          cd /__w/lunaos-repo
          git clone https://aur.archlinux.org/8188eu-dkms.git
          cd /__w/lunaos-repo/8188eu-dkms
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build PortProton
        run: |
          cd /__w/lunaos-repo
          git clone https://aur.archlinux.org/portproton.git 
          cd /__w/lunaos-repo/portproton
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -d"

      - name: Build StartWine
        run: |
          cd /__w/lunaos-repo
          git clone https://aur.archlinux.org/startwine.git 
          cd /__w/lunaos-repo/startwine
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build Winetricks
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/winetricks.git 
          cd /__w/lunaos-repo/winetricks
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build LunaOS Hooks
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-core-pkgbuilds/system/base/lunaos-hooks.git 
          cd /__w/lunaos-repo/lunaos-hooks
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build LunaOS GRUB theme
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/lunaos-grub-theme.git
          cd /__w/lunaos-repo/lunaos-grub-theme
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -d"

      - name: Build GRUB Meta
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/meta-packages/grub-meta.git
          cd /__w/lunaos-repo/grub-meta
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -d"

      - name: Build Kvantm LibAdwaita theme
        run: |
          cd /__w/lunaos-repo
          git clone https://aur.archlinux.org/kvantum-theme-libadwaita-git.git
          cd /__w/lunaos-repo/kvantum-theme-libadwaita-git
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build Kvantum Colloid theme
        run: |
          cd /__w/lunaos-repo
          git clone https://gitlab.com/LunaOS/pkgbuilds/lunaos-extra-pkgbuilds/gnome/colloid-kvantum-theme.git
          cd /__w/lunaos-repo/colloid-kvantum-theme
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build winesync-dkms
        run: |
          cd /__w/lunaos-repo
          git clone https://aur.archlinux.org/winesync.git
          cd /__w/lunaos-repo/winesync
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Build asusctl
        run: |
          cd /__w/lunaos-repo
          git clone https://aur.archlinux.org/asusctl.git
          cd /__w/lunaos-repo/asusctl
          chown user -R ..
          su user -c "yes '' | makepkg --noconfirm -s"

      - name: Sign lunaos repo
        run: |
          cd $PKGDEST
          sh /__w/lunaos-repo/sign.sh

      - name: Update lunaos repo
        run: |
          cd $PKGDEST
          sh /__w/lunaos-repo/update-repo.sh

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release all packages to GitHub Releases Mirror
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: lunaos-repo
          files: /tmp/lunaos-repo/*


      - name: GitLab Sync
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitlab.com:LunaOS/lunaos-repo.git
          ssh_private_key: "${{ secrets.GITLAB_SYNC }}"
